site_name: Manchester HacSpace - Laser PCB
pages:
- Home: index.md
- Design:
    - KiCad - PCB Part 1: Design/KiCad-Pcb1.md
    - KiCad - PCB Part 2: Design/KiCad-Pcb2.md
    - KiCad - Exporting Gerbers: Design/KiCad-GerberExport.md
    - FlatCAM - Single Sided Boards: Design/FlatCAM-SingleSided.md
    - KiCad - Exporting as SVG: Design/KiCad-Svg.md

- Etching:
    - Cleaning the Board: Etching/Cleaning-Board.md
    - Prepping the Board: Etching/CopperBoard-Prep.md
    - Laser Engraving: Etching/Laser-Engraving.md
    - Etching Tank: Etching/Etching-Tank.md

- Mask:
    - Solder Paste Mylar: Mask/SolderPaste-Stencil.md
    - Solder Mask: Mask/SolderMask.md

- Misc:
    - Further Ideas: Misc/Further-Ideas.md
    - Links: Misc/Links.md

theme: united
#theme: alabaster
#theme: readthedocs
#theme: mkdocs

markdown_extensions:
    - smarty

extra_css:
    - css/highlight-fix.css
    - css/highlight-custom.css
