site_name: Manchester HacSpace - Laser PCB
pages:
- Home: index.md
- KiCad:
    - KiCad - Library Management: KiCad/KiCad-LibraryMgmt.md
    - KiCad - Schematic to PCB: KiCad/KiCad-SchematicPCB.md
    - KiCad - Edge Border: KiCad/KiCad-EdgeBorder.md
    - KiCad - Design Rules: KiCad/KiCad-DesignRules.md
    - KiCad - Parts Placement: KiCad/KiCad-PartsPlacement.md
    - KiCad - Routing: KiCad/KiCad-Routing.md
    - KiCad - Exporting Gerbers: KiCad/KiCad-ExportGerber.md
    - KiCad - Exporting as SVG: KiCad/KiCad-ExportSvg.md

- FlatCAM:
    - FlatCAM - Single Sided Boards: FlatCam/FlatCam-SingleSided.md

- Etching:
    - Cleaning the Board: Etching/Cleaning-Board.md
    - Prepping the Board: Etching/CopperBoard-Prep.md
    - Laser Engraving: Etching/Laser-Engraving.md
    - Etching Tank: Etching/Etching-Tank.md

- Mask:
    - Solder Paste Mylar: Mask/SolderPaste-Stencil.md
    - Solder Mask: Mask/SolderMask.md

- Misc:
    - Further Ideas: Misc/Further-Ideas.md
    - Links: Misc/Links.md

theme: united
#theme: alabaster
#theme: readthedocs
#theme: mkdocs

markdown_extensions:
    - smarty

extra_css:
    - css/highlight-fix.css
    - css/highlight-custom.css
